"""
A design's firmware as a PlatformIO project. Stage 5.

`brain/decisions.md` [2026-09-23] Stage 5, item 7: firmware is shown only once
it has compiled, and what compiles is a project — `platformio.ini` beside
`src/main.ino` — not a loose sketch. Platform and library versions are pinned,
so the same design builds the same way next month; the project's SHA-256 is
the key its build result is cached under.

Deterministic, like everything a generator emits: same design, same bytes,
same hash.
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass
from typing import Dict, Optional, Tuple

from core.ir_schema import CircuitIR, ComponentType
from generators.firmware.arduino import ArduinoFirmwareGenerator

#: The platform versions the compile gate was verified with.
PLATFORM_VERSIONS = {"atmelavr": "5.3.0", "espressif32": "7.1.3", "ststm32": "20.0.0"}

#: Libraries each template needs, pinned.
LIBRARIES: Dict[str, Tuple[str, ...]] = {
    "sensor_read.ino.j2": ("adafruit/DHT sensor library@1.4.6", "adafruit/Adafruit Unified Sensor@1.1.15"),
    "modbus_master.ino.j2": ("4-20ma/ModbusMaster@2.0.1",),
}


@dataclass(frozen=True)
class FirmwareProject:
    target: str                    # data/mcu_targets id
    board: str                     # human name
    files: Tuple[Tuple[str, str], ...]   # (path, content), sorted

    @property
    def hash(self) -> str:
        h = hashlib.sha256()
        for path, content in self.files:
            h.update(path.encode("utf-8") + b"\0" + content.encode("utf-8") + b"\0")
        return h.hexdigest()

    def file(self, path: str) -> str:
        return dict(self.files)[path]

    @property
    def source(self) -> str:
        return self.file("src/main.ino")


def platformio_ini(target, libraries: Tuple[str, ...]) -> str:
    lines = [
        f"; Generated by Circuit OS for the {target.board}. Build with: pio run",
        f"[env:{target.id}]",
        f"platform = {target.platform}@{PLATFORM_VERSIONS[target.platform]}",
        f"board = {target.pio_board}",
        "framework = arduino",
        "monitor_speed = 115200",
    ]
    if libraries:
        lines.append("lib_deps =")
        lines += [f"    {lib}" for lib in libraries]
    if target.build_flags:
        lines.append("build_flags =")
        lines += [f"    {flag}" for flag in target.build_flags]
    return "\n".join(lines) + "\n"


def project_for(ir: CircuitIR) -> Optional[FirmwareProject]:
    """The design's firmware project, or None for a design with no microcontroller."""
    if not any(c.type == ComponentType.MICROCONTROLLER for c in ir.components):
        return None
    generator = ArduinoFirmwareGenerator()
    target = generator.target(ir)
    source = generator.generate(ir)
    libraries = LIBRARIES.get(generator.template_for(ir), ())
    files = (("platformio.ini", platformio_ini(target, libraries)), ("src/main.ino", source))
    return FirmwareProject(target=target.id, board=target.board, files=tuple(sorted(files)))
