"""analyze.py — robustness experiments E1–E10 from results.jsonl + items/*.json. Writes RESULTS.md."""
import collections, json, pathlib, statistics as st
st_mean = st.mean
H = pathlib.Path(__file__).resolve().parent
NMI = "need_more_information"
rows = [json.loads(l) for l in (H / "results.jsonl").read_text().splitlines() if l.strip()]
ok = [r for r in rows if not r.get("error") and r.get("answers")]
items = {}
for f in (H / "items").glob("E*.json"):
    d = json.loads(f.read_text())
    for q in d["requests"]:
        items[(d["experiment"], q["item_id"], q["variant"])] = q
def by(exp): return [r for r in ok if r["experiment"] == exp]
def meta(r): return items.get((r["experiment"], r["item_id"], r["variant"].split(":")[0]), {}).get("meta", {})
def ch(a): return a.get("choice")
def ptop(a): return max(a["probabilities"].values())
def pct(k, n): return f"{k}/{n} = {100*k/n:.1f} %" if n else "—"
out = ["# Robustness, determinism, limits — results\n",
       "Generated by `analyze.py` from `results.jsonl` against item sets pre-registered in `items/PREREGISTRATION.tsv`. Model `jev-1.13.0`.\n"]
W = out.append
lat = [r["latency_ms"] for r in ok if r.get("latency_ms")]
tin = sum((r.get("usage") or {}).get("input_tokens") or 0 for r in ok); tout = sum((r.get("usage") or {}).get("output_tokens") or 0 for r in ok)
W(f"## Run\n\n{len(rows)} requests logged, {len(rows)-len(ok)} errors; {tin:,} input / {tout:,} output tokens. "
  f"Latency ms: median {st.median(lat):.0f}, p90 {sorted(lat)[int(.9*len(lat))]:.0f}, max {max(lat):.0f}.\n")
errs = [r for r in rows if r.get("error")]
for r in errs: W(f"- error: {r['experiment']} {r['item_id']} {r['variant']} → {str(r['error'].get('body'))[:120]}")

# E1a confidence vs k
W("\n## E1a — does `confidence` move when dead options are added?\n")
tab = collections.defaultdict(lambda: [[], [], 0, 0])
for r in by("E1a_conf_k"):
    m = meta(r)
    for k, a in r["answers"].items():
        t = tab[k]; t[0].append(a["confidence"]); t[1].append(a["probabilities"].get(m["truth"], 0)); t[2] += ch(a) == m["truth"]; t[3] += 1
W("| k | mean confidence | mean P(truth) | accuracy |\n|---|---|---|---|")
for k in sorted(tab, key=lambda x: int(x[1:])):
    c, p, a, n = tab[k]; W(f"| {k[1:]} | {st.mean(c):.3f} | {st.mean(p):.3f} | {pct(a, n)} |")

# E2 determinism
W("\n## E2 — determinism (one fixed 20-question request, repeated)\n")
e2 = by("E2_determinism")
per = collections.defaultdict(list)
for r in e2:
    for k, a in r["answers"].items():
        per[k].append(json.dumps(a.get("probabilities") or a.get("noul"), sort_keys=True))
distinct = {k: len(set(v)) for k, v in per.items()}
W(f"{len(e2)} repeats (variants: {dict(collections.Counter(r['variant'].split('#')[0] for r in e2))}). "
  f"Questions with byte-identical answers on every repeat: {sum(v == 1 for v in distinct.values())}/{len(distinct)}. "
  f"Max distinct answers for one question: {max(distinct.values())}.")
dups = [k for k in ("pulldown_option", "dup_a", "zz_dup_b") if k in per]
if dups:
    W(f"Exact duplicate questions under different names ({', '.join(dups)}) got identical answers within the same request in "
      f"{sum(len({json.dumps(r['answers'][k].get('probabilities'), sort_keys=True) for k in dups}) == 1 for r in e2)}/{len(e2)} requests.")

def _am(a):
    return a.get("choice") if a["type"] == "choice" else (a["noul"] > .5 if a["type"] == "noul" else a.get("score"))
def _vals(a):
    return a["probabilities"] if a["type"] == "choice" else {"p": a.get("noul", a.get("score"))}
flipq = []
for k in per:
    v = [r["answers"][k] for r in e2]
    sp = max(max(_vals(a)[l] for a in v) - min(_vals(a)[l] for a in v) for l in _vals(v[0]))
    if v[0]["type"] == "score":
        flipq.append(f"{k}: score (expected value) ranged {min(a['score'] for a in v):.2f}–{max(a['score'] for a in v):.2f} over {len(v)} repeats")
    elif len({_am(a) for a in v}) > 1:
        flipq.append(f"{k}: top answer FLIPPED, {collections.Counter(str(_am(a)) for a in v).most_common()} (prob spread {sp:.2f})")
W(f"\nChoice/Noul questions whose top answer flipped between identical repeats: {sum('FLIPPED' in f for f in flipq)}; score drift listed too:")
for f in flipq: W(f"- {f}")

# E3 order
W("\n## E3 — option order (same question, 6 option orders in one request)\n")
st3 = collections.Counter(); spread = []
for r in by("E3_order"):
    m = meta(r); cs = [ch(a) for a in r["answers"].values()]
    pt = [a["probabilities"].get(m.get("truth"), 0) for a in r["answers"].values()] if m.get("truth") else []
    kind = "known" if m.get("truth") else "judgment"
    st3[(kind, "stable")] += len(set(cs)) == 1; st3[(kind, "n")] += 1
    if pt: st3["correct_all"] += all(c == m["truth"] for c in cs); st3["correct_any"] += any(c == m["truth"] for c in cs); spread.append(max(pt) - min(pt))
W(f"Known-answer items with the same argmax in all 6 orders: {pct(st3[('known','stable')], st3[('known','n')])}; judgment items: {pct(st3[('judgment','stable')], st3[('judgment','n')])}. "
  f"Known items correct in all 6 orders: {pct(st3['correct_all'], st3[('known','n')])} (correct in at least one: {st3['correct_any']}). "
  f"P(truth) max−min across orders: median {st.median(spread):.2f}, max {max(spread):.2f}.")

# E4 paraphrase
W("\n## E4 — paraphrase (4 state wordings × 4 instruction wordings)\n")
g = collections.defaultdict(list)
for r in by("E4_paraphrase"):
    m = meta(r)
    for a in r["answers"].values(): g[r["item_id"]].append((ch(a), m.get("truth")))
known = {i: v for i, v in g.items() if v[0][1]}; judg = {i: v for i, v in g.items() if not v[0][1]}
W(f"Known items: argmax identical across all 16 wordings {pct(sum(len({c for c,_ in v})==1 for v in known.values()), len(known))}; "
  f"answer accuracy over all wordings {pct(sum(c==t for v in known.values() for c,t in v), sum(len(v) for v in known.values()))}. "
  f"Judgment items stable across 16 wordings: {pct(sum(len({c for c,_ in v})==1 for v in judg.values()), len(judg))}.")

# E5 polarity
W("\n## E5 — polarity (Noul x vs Noul not-x)\n")
sums, flips, nacc, n5 = [], 0, 0, 0
for r in by("E5_polarity"):
    a = r["answers"]; m = meta(r)
    if "noul_x" in a and "noul_notx" in a:
        px, pn = a["noul_x"]["noul"], a["noul_notx"]["noul"]; sums.append(px + pn)
        flips += (px > .5) == (pn > .5)
        if m.get("truth_x") is not None: nacc += (px > .5) == m["truth_x"]; n5 += 1
if sums:
    W(f"{len(sums)} pairs. P(x)+P(not x): median {st.median(sums):.2f}, pairs off by >0.15: {sum(abs(s-1)>.15 for s in sums)}, "
      f"pairs where both sides land on the same side of 0.5 (incoherent): {flips}. Noul-x accuracy on known items: {pct(nacc, n5)}.")
else:
    W("question names: " + ", ".join(sorted({k for r in by('E5_polarity') for k in r['answers']})))

# E6 authority
W("\n## E6 — authority / social cues in the state\n")
acc = collections.defaultdict(lambda: [0, 0, 0])
for r in by("E6_authority"):
    m = meta(r)
    for a in r["answers"].values():
        t = acc[r["variant"]]; t[0] += ch(a) == m["truth"]; t[1] += ch(a) == m["wrong"]; t[2] += 1
W("| cue | accuracy | chose the cued wrong option |\n|---|---|---|")
for v, (c, w, n) in sorted(acc.items()): W(f"| {v} | {pct(c, n)} | {pct(w, n)} |")

# E7 distractors
W("\n## E7 — irrelevant project text added to the state\n")
base = {(r["item_id"]): r for r in by("E6_authority") if r["variant"] == "neutral_none"}
acc = collections.defaultdict(lambda: [0, 0])
for r in base.values():
    m = meta(r)
    for a in r["answers"].values(): acc["baseline"][0] += ch(a) == m["truth"]; acc["baseline"][1] += 1
for r in by("E7_distractors"):
    m = meta(r)
    for a in r["answers"].values(): acc[r["variant"]][0] += ch(a) == m["truth"]; acc[r["variant"]][1] += 1
W("| variant | accuracy |\n|---|---|")
for v, (c, n) in acc.items(): W(f"| {v} | {pct(c, n)} |")

# E8 batching
W("\n## E8 — batching (target alone vs inside 10 / 50 questions)\n")
g = collections.defaultdict(dict)
for r in by("E8_batching"):
    m = meta(r); a = r["answers"]["target"]
    g[r["item_id"]][r["variant"]] = (ch(a), a["probabilities"].get(m.get("truth"), None), m.get("truth"))
W("| item | " + " | ".join(sorted(next(iter(g.values())))) + " |\n|" + "---|" * (1 + len(next(iter(g.values())))))
for i, d in g.items():
    W(f"| {i} (truth {d[next(iter(d))][2]}) | " + " | ".join(f"{d[v][0]}" + (f" ({d[v][1]:.2f})" if d[v][1] is not None else "") for v in sorted(d)) + " |")

# E9 NMI
W("\n## E9 — does Jev abstain when the decisive fact is removed?\n")
acc = collections.defaultdict(lambda: [0, 0, 0])
for r in by("E9_nmi"):
    m = meta(r)
    for k, a in r["answers"].items():
        t = acc[(m["answerable"], k)]; t[2] += 1
        t[0] += ch(a) == m["truth"]; t[1] += ch(a) == NMI
W("| case | question form | chose truth | chose need_more_information |\n|---|---|---|---|")
for (ans, k), (c, nm, n) in sorted(acc.items()): W(f"| {'answerable' if ans else 'fact removed'} | {k} | {pct(c, n)} | {pct(nm, n)} |")

# E10 scaling
W("\n## E10 — state-size scaling (planted needles)\n")
W("| target state tokens | input tokens | choice accuracy | noul accuracy | absent → not_stated |\n|---|---|---|---|---|")
for r in sorted(by("E10_scaling"), key=lambda r: (int(r["variant"][1:]), r["item_id"])):
    tr = meta(r)["truth"]; a = r["answers"]
    cc = [k for k in tr if k.startswith("c") and tr[k] != "not_stated"]; nn = [k for k in tr if k.startswith("n") and tr[k]]
    ab = [k for k in tr if k.startswith("c") and tr[k] == "not_stated"]
    W(f"| {r['variant'][1:]} ({r['item_id']}) | {r['usage']['input_tokens']:,} | {sum(ch(a[k])==tr[k] for k in cc)}/{len(cc)} | "
      f"{sum(a[k]['noul']>.5 for k in nn)}/{len(nn)} | {sum(ch(a[k])=='not_stated' for k in ab)}/{len(ab)} |")

# ── late-registered lure / judgment sets and E2 phases ──────────────────────
W("\n## Late-registered sets (built after the main registration, registered and hashed before any call)\n")
W("### E2 by phase (same fixed request)\n")
W("| phase | n | resolved model | pulldown_option argmax | P(add_as_opt_in_constraint) range |\n|---|---|---|---|---|")
for ph in ("now_seq", "now_conc8", "later_seq", "aliases"):
    rr = [r for r in e2 if r["variant"].startswith(ph)]
    if not rr: continue
    for model in sorted({r.get("model_requested") for r in rr}):
        m = [r for r in rr if r.get("model_requested") == model]
        ps = [r["answers"]["pulldown_option"]["probabilities"]["add_as_opt_in_constraint"] for r in m]
        W(f"| {ph} ({model}) | {len(m)} | {sorted({r['model_resolved'] for r in m})} | {dict(collections.Counter(r['answers']['pulldown_option']['choice'] for r in m))} | {min(ps):.2f}–{max(ps):.2f} |")
def lure_acc(exp, variant=None):
    c = w = n = 0
    for r in by(exp):
        if variant and r["variant"] != variant: continue
        m = meta(r)
        for a in r["answers"].values():
            n += 1; c += ch(a) == m["truth"]; w += ch(a) == m["wrong"]
    return c, w, n
W("\n### Lure items (24 known answers with a strong pre-registered wrong option)\n")
W("| condition | correct | chose the lure |\n|---|---|---|")
c, w, n = lure_acc("E3h_order_lure"); W(f"| 6 option orders | {pct(c, n)} | {pct(w, n)} |")
st = sum(len({ch(a) for a in r["answers"].values()}) == 1 for r in by("E3h_order_lure")); W(f"| same argmax in all 6 orders | {pct(st, len(by('E3h_order_lure')))} | |")
for v in ("neutral_none", "owner_right", "owner_wrong", "council_wrong"):
    c, w, n = lure_acc("E6h_authority_lure", v); W(f"| cue: {v} | {pct(c, n)} | {pct(w, n)} |")
for v in ("d200_after", "d200_before"):
    c, w, n = lure_acc("E7h_distractors_lure", v); W(f"| 200 % irrelevant text {v[5:]} | {pct(c, n)} | {pct(w, n)} |")
acc = collections.defaultdict(lambda: [0, 0, 0])
for r in by("E9h_nmi_lure"):
    m = meta(r)
    for k, a in r["answers"].items():
        t = acc[k]; t[0] += ch(a) == m["truth"]; t[1] += ch(a) == NMI; t[2] += 1
for k, (c, nm, n) in acc.items(): W(f"| answerable, form {k} | {pct(c, n)} | false abstain {pct(nm, n)} |")
W("\n### E6j — authority cues on judgment items (no truth; does the answer move to the cued runner-up?)\n")
W("| cue | answers equal to the cued option | answers equal to the uncued baseline argmax |\n|---|---|---|")
base6 = {}
for r in by("E6j_authority_judgment"):
    if r["variant"] == "neutral_none": base6[r["item_id"]] = ch(r["answers"]["q_fwd"])
agg = collections.defaultdict(lambda: [0, 0, 0])
for r in by("E6j_authority_judgment"):
    m = meta(r); tgt = m.get("cue_target") or m["e3_baseline"]["target"]
    for a in r["answers"].values():
        t = agg[r["variant"]]; t[0] += ch(a) == tgt; t[1] += ch(a) == base6.get(r["item_id"]); t[2] += 1
for v, (c, b, n) in sorted(agg.items()): W(f"| {v} | {pct(c, n)} | {pct(b, n)} |")
W("\n### E1c — dead options on judgment items (mid-range p_top)\n")
W("| dead options added | mean confidence | mean p_top | argmax same as with 0 dead |\n|---|---|---|---|")
g = collections.defaultdict(lambda: [[], [], 0, 0])
for r in by("E1c_conf_k_judgment"):
    a0 = ch(r["answers"]["dead0"])
    for k, a in r["answers"].items():
        t = g[k]; t[0].append(a["confidence"]); t[1].append(ptop(a)); t[2] += ch(a) == a0; t[3] += 1
for k in sorted(g, key=lambda x: int(x[4:])):
    c_, p_, s_, n_ = g[k]; W(f"| {k[4:]} | {st_mean(c_):.3f} | {st_mean(p_):.3f} | {pct(s_, n_)} |")
(H / "RESULTS.md").write_text("\n".join(out) + "\n")
print("\n".join(out))
