"""analyze.py — devflow tasks (T1 entry↔commit, T2 failure class, T3 doc drift, Q entry shape, T4 owner
attention, CONV commit convention): Jev vs pre-registered label, vs the deterministic baseline, and
stability across orig / rev (reversed options) / rep (repeat). Writes RESULTS.md."""
import collections, json, pathlib
H = pathlib.Path(__file__).resolve().parent
R = [json.loads(l) for l in (H / "results.jsonl").read_text().splitlines() if l.strip()]
SETS = {"T1": "t1_entry_covers", "T2": "t2_failure_class", "T3": "t3_doc_drift", "Q": "q_entry_quality",
        "T4": "t4_owner_attention", "CONV": "conv_commit_subjects"}
items = {t: {x["item_id"]: x for x in map(json.loads, (H / "sets" / f"{f}.jsonl").read_text().splitlines()) if x}
         for t, f in SETS.items()}
ans = collections.defaultdict(dict)
for r in R:
    ans[(r["task"], r["item_id"])][r["variant"]] = r["answers"]
MAIN = {"T1": "entry_covers_diff", "T2": "failure_class", "T4": "needs_owner_attention", "CONV": "commit_convention"}
def pct(k, n): return f"{k}/{n} = {100*k/n:.0f} %" if n else "—"
out = ["# Devflow tasks — results\n", "Generated by `analyze.py` from `results.jsonl` and the pre-registered `sets/`. "
       "`orig`, `rev` (option order reversed), `rep` (repeat) are three sends of each item. Model `jev-1.13.0`.\n"]
W = out.append
W(f"{len(R)} requests. Input tokens {sum(r['usage']['input_tokens'] for r in R):,}.\n")
W("## Choice tasks\n")
W("| Task | n | Jev accuracy (orig) | Jev accuracy (explicit wording) | deterministic baseline | stable orig/rev/rep | accuracy when p_top ≥ 0.9 (coverage) | ≥0.9 and stable across 3 |\n|---|---|---|---|---|---|---|---|")
confusions = {}
for t, q in MAIN.items():
    n = c = ce = ne = d = nd = s = hi = hic = hs = hsc = 0
    conf = collections.Counter()
    for iid, it in items[t].items():
        a = ans.get((t, iid), {})
        if "orig" not in a: continue
        lab = it["label"]; o = a["orig"][q]; n += 1; c += o["choice"] == lab
        conf[(lab, o["choice"])] += 1
        if q + "_explicit" in a["orig"]: ne += 1; ce += a["orig"][q + "_explicit"]["choice"] == lab
        db = (it.get("det_baseline") or {}).get("label")
        if db: nd += 1; d += db == lab
        chs = {a[v][q]["choice"] for v in ("orig", "rev", "rep") if v in a}
        st = len(chs) == 1; s += st
        pt = max(o["probabilities"].values())
        if pt >= .9: hi += 1; hic += o["choice"] == lab
        if st and all(max(a[v][q]["probabilities"].values()) >= .9 for v in ("orig", "rev", "rep") if v in a):
            hs += 1; hsc += o["choice"] == lab
    confusions[t] = conf
    W(f"| {t} {q} | {n} | {pct(c, n)} | {pct(ce, ne)} | {pct(d, nd)} | {pct(s, n)} | {pct(hic, hi)} ({hi}/{n}) | {pct(hsc, hs)} ({hs}/{n}) |")
W("\nDeterministic baselines: T1 path/mention rule; T2 the earlier report's regex spec (its 'unmatched' counts as wrong); T4 path/keyword routing. CONV has no baseline (its label *is* a regex).\n")
W("### Where Jev is wrong (orig; label → Jev answer: count)\n")
for t, conf in confusions.items():
    wrong = [f"{l}→{j}: {k}" for (l, j), k in conf.most_common() if l != j]
    W(f"- **{t}**: " + ("; ".join(wrong) if wrong else "none"))

W("\n## T3 — doc drift (does a doc sentence contradict a derived fact?)\n")
n = cj = cn = cc = dn = dd = 0
for iid, it in items["T3"].items():
    a = ans.get(("T3", iid), {}).get("orig")
    if not a: continue
    lab = bool(it["label"]); n += 1
    cj += (a["drift_status"]["choice"] == "contradicts_current_fact") == lab
    cn += (a["contradicts_derived_fact"]["noul"] > .5) == lab
    dn += bool(it["det_naive"]["flag"]) == lab; dd += bool(it["det_dated"]["flag"]) == lab
W(f"| Method | accuracy (n={n}, {sum(bool(i['label']) for i in items['T3'].values())} true drifts) |\n|---|---|\n"
  f"| Jev choice `drift_status` = contradicts | {pct(cj, n)} |\n| Jev noul `contradicts_derived_fact` > 0.5 | {pct(cn, n)} |\n"
  f"| regex vs facts (naive) | {pct(dn, n)} |\n| regex vs facts, dated sentences skipped | {pct(dd, n)} |")
by_type = collections.defaultdict(lambda: [0, 0, 0])
for iid, it in items["T3"].items():
    a = ans.get(("T3", iid), {}).get("orig")
    if a:
        t = by_type[it["type"]]; t[2] += 1
        t[0] += (a["drift_status"]["choice"] == "contradicts_current_fact") == bool(it["label"]); t[1] += bool(it["det_dated"]["flag"]) == bool(it["label"])
W("\n| item type | Jev choice | regex (dated) |\n|---|---|---|")
for k, (j, d_, m) in by_type.items(): W(f"| {k} (n={m}) | {pct(j, m)} | {pct(d_, m)} |")

W("\n## Q — decisions.md entry shape (score 0–5 vs deterministic checklist)\n")
real = [(it, ans[("Q", iid)]["orig"]) for iid, it in items["Q"].items() if it.get("kind") == "real" and ("Q", iid) in ans]
if real:
    ex = sum(round(a["entry_shape"]["score"]) == it["checklist"]["score"] for it, a in real)
    w1 = sum(abs(a["entry_shape"]["score"] - it["checklist"]["score"]) <= 1 for it, a in real)
    el = collections.Counter(); eln = 0
    for it, a in real:
        for k, v in it["checklist"]["elements"].items():
            if "el_" + k in a: eln += 1; el[k] += (a["el_" + k]["noul"] > .5) == v
    W(f"Real entries: {len(real)}. Rounded Jev score equals checklist score: {pct(ex, len(real))}; within ±1: {pct(w1, len(real))}. "
      f"Per-element noul agreement with the checklist: {pct(sum(el.values()), eln)} ({', '.join(f'{k} {v}' for k, v in el.items())} of {len(real)} each).")
pairs = [(it, items["Q"].get(it.get("pair_of"))) for it in items["Q"].values() if it.get("kind") not in ("real", None) and it.get("pair_of")]
okp = sum(ans[("Q", d["item_id"])]["orig"]["entry_shape"]["score"] < ans[("Q", o["item_id"])]["orig"]["entry_shape"]["score"]
          for d, o in pairs if o and ("Q", d["item_id"]) in ans)
W(f"Degraded copies (one element deleted) scored lower than their original: {pct(okp, len(pairs))}.")

W("\n## Context ablations\n")
for t, v in (("T1", "blind_partial"), ("T1", "unpacked_template"), ("T3", "blind_partial")):
    k = c = 0
    for iid, it in items[t].items():
        a = ans.get((t, iid), {}).get(v)
        if not a: continue
        k += 1
        if t == "T1": c += a.get("entry_covers_diff", a.get(next(iter(a))))["choice"] in (it["label"],)
        else: c += (a["drift_status"]["choice"] == "contradicts_current_fact") == bool(it["label"])
    W(f"- {t} `{v}`: {pct(c, k)} correct " + ("(entry removed: correct answer should become need_more_information/unrelated, so low is expected)" if v == "blind_partial" and t == "T1" else ""))
(H / "RESULTS.md").write_text("\n".join(out) + "\n")
print("\n".join(out))
