"""P1 — net_role labels for generic nets, described only by their connections.

Truth by construction: each net is written as the circuit fragment that implements the role
named by the label, using the template's own label definitions (B14, phase3_labels.questions.json).
Out-of-set nets (roles the label set does not contain) are scored separately.
"""
from common import cite, pick_subset, write_set

QUESTIONS = {
    "net_role": {
        "type": "choice",
        "instructions": "What role does net {net} play, given its connections?",
        "criteria": {
            "analog_0_10v_out": "Drives a 0-10 V control input.",
            "loop_4_20ma": "Part of a 4-20 mA current loop.",
            "relay_coil_drive": "Switches a relay coil.",
            "field_input_24v": "Receives a 24 V field signal.",
            "logic_local": "Board-local logic only.",
            "undeclared": "The connections do not determine the role.",
        },
    }
}

# (id, truth, difficulty, net, pins_on_net, one_hop, field_wiring, derivation)
ITEMS = [
    # ── analog_0_10v_out ──────────────────────────────────────────────────
    ("A01", "analog_0_10v_out", "explicit", "AO1",
     ["U4 pin 1 (LM358 op-amp output; U4 supplied from +24 V)", "R21 pin 1 (100 ohm series resistor)", "R22 pin 1 (20 kohm feedback resistor)"],
     ["R21 pin 2 goes to screw terminal J3 pin 1", "R22 pin 2 goes to U4 inverting input, with R23 (9.9 kohm) from there to GND",
      "U4 non-inverting input is fed from MCU PWM pin PB6 through a two-pole RC filter"],
     "J3 pin 1 is wired to terminal AI1 of a variable-frequency drive; AI1 is the drive's speed-reference input, 0-10 V, 10 kohm input impedance",
     "Op-amp gain 1+20k/9.9k = 3.02 on a 0-3.3 V filtered PWM gives 0-10 V into a VFD 0-10 V input: drives a 0-10 V control input."),
    ("A02", "analog_0_10v_out", "implicit", "OUT_A",
     ["U2 pin 7 (LM2904 op-amp output; U2 supplied from +15 V)", "R8 pin 1 (47 ohm)"],
     ["R8 pin 2 goes to terminal J1 pin 2, which also has a 12 V TVS diode to GND", "J1 pin 1 is GND",
      "U2 is configured as a non-inverting amplifier with gain 3.0 (R9 20 kohm, R10 10 kohm)",
      "U2 input is the 0-3.3 V output of the MCU's DAC"],
     None,
     "A 0-3.3 V DAC scaled by 3.0 gives 0-9.9 V at a field terminal with a GND return: an analog 0-10 V output."),
    ("A03", "analog_0_10v_out", "explicit", "DAMPER_CMD",
     ["U9 pin VOUT (AD5422 DAC, voltage output configured for the 0 V to 10 V range)", "J5 pin 3"],
     ["J5 pin 4 is GND"],
     "J5 pin 3 is wired to input Y of a damper actuator (control signal 0-10 V DC)",
     "DAC configured 0-10 V into an actuator's 0-10 V control input."),
    ("A04", "analog_0_10v_out", "implicit", "N14",
     ["U3 output (op-amp supplied from +15 V)", "R30 pin 1 (220 ohm)", "R31 pin 1 (10 kohm feedback)"],
     ["R30 pin 2 goes to J8 pin 1, labelled SIG; J8 pin 2, labelled COM, is GND",
      "R31 pin 2 goes to U3 inverting input with R32 (4.99 kohm) to GND (gain 3.0)",
      "U3 non-inverting input is a 0-3.3 V filtered PWM signal"],
     None,
     "Gain-3 buffer of a 0-3.3 V signal to a SIG/COM terminal pair: 0-10 V analog output."),
    ("A05", "analog_0_10v_out", "explicit", "SPEED_REF",
     ["Q5 emitter (NPN, collector at +12 V, base driven by op-amp U6 which closes the loop from Q5's emitter)", "J2 pin 4"],
     ["U6 reference input is 0-3.3 V from the MCU DAC with a loop gain of 3.03", "J2 pin 5 is GND"],
     "J2 pin 4 is wired to the control input of an EC fan motor (0-10 V DC, 100 kohm input)",
     "Closed-loop emitter-follower stage to an EC fan's 0-10 V control input."),
    ("A06", "analog_0_10v_out", "explicit", "VFD_REF",
     ["U11 pin 1 (LT1013 op-amp output; supplied from +24 V)", "R40 pin 1 (100 ohm)"],
     ["R40 pin 2 goes to terminal J7 pin 1; J7 pin 2 is GND"],
     "J7 is wired to a VFD analog input that has been configured for 'voltage, 0-10 V'",
     "Op-amp output on a 24 V rail into a VFD analog input configured 0-10 V."),
    ("A07", "analog_0_10v_out", "implicit", "N31",
     ["U14 output (OPA192 op-amp on +/-15 V)", "R50 pin 1 (49.9 ohm)", "R51 pin 1 (30 kohm feedback)"],
     ["R50 pin 2 goes to J12 pin 1; J12 pin 2 is GND", "R51 pin 2 goes to U14 inverting input with R52 (10 kohm) to GND (gain 4.0)",
      "U14 non-inverting input is a 16-bit DAC output spanning 0-2.5 V"],
     None,
     "0-2.5 V DAC times gain 4.0 gives 0-10 V at a field terminal."),
    ("A08", "analog_0_10v_out", "explicit", "VALVE_Y",
     ["Output pin of a PWM-to-voltage converter module (0-10 V output, 5 mA max)", "J4 pin 1"],
     ["the converter's input is MCU PWM pin D9", "J4 pin 2 is GND"],
     "J4 pin 1 is wired to input 'Y 0(2)-10 V' of a valve actuator",
     "Converter module rated 0-10 V output into a valve actuator's 0(2)-10 V input."),
    # ── loop_4_20ma ───────────────────────────────────────────────────────
    ("L01", "loop_4_20ma", "explicit", "AI0",
     ["J2 pin 1", "R5 pin 1 (250 ohm 0.1% resistor; R5 pin 2 is GND)", "R6 pin 1 (10 kohm)"],
     ["R6 pin 2 goes to ADC input A0 with 100 nF to GND", "J2 pin 2 is +24 V"],
     "J2 is wired to a two-wire pressure transmitter, 4-20 mA, loop-powered from J2 pin 2",
     "Loop-powered 4-20 mA transmitter returning through a 250 ohm sense resistor (1-5 V at the ADC)."),
    ("L02", "loop_4_20ma", "implicit", "SENSE1",
     ["F3 pin 2 (PTC fuse; F3 pin 1 is terminal J6 pin 2)", "R11 pin 1 (250 ohm 0.1%; R11 pin 2 is GND)",
      "D4 cathode (TVS; anode to GND)", "R12 pin 1 (22 kohm)"],
     ["R12 pin 2 goes to MCU ADC input A1", "J6 pin 1 is +24 V"],
     None,
     "A field terminal adjacent to +24 V returning through a precision 250 ohm resistor to GND: a 4-20 mA receiver."),
    ("L03", "loop_4_20ma", "explicit", "PT_OUT",
     ["U3 pin IOUT (XTR115 4-20 mA current-loop transmitter)", "J3 pin 2"],
     ["J3 pin 1 is the loop positive", "U3 input is driven by the MCU's DAC"],
     "J3 is wired to a PLC analog input configured for 4-20 mA",
     "XTR115 current output into a PLC's 4-20 mA input."),
    ("L04", "loop_4_20ma", "implicit", "N22",
     ["R17 pin 2 (100 ohm; R17 pin 1 is terminal J9 pin 2)", "R18 pin 1 (249 ohm 0.1%; R18 pin 2 is AGND)", "R19 pin 1 (10 kohm)"],
     ["R19 pin 2 goes to ADC input A2 with 100 nF to AGND", "J9 pin 1 is +24 V", "firmware comment beside A2 reads 'expect 1.0-5.0 V'"],
     None,
     "249 ohm precision shunt from a field terminal, 1.0-5.0 V expected: 4-20 mA x 249 ohm."),
    ("L05", "loop_4_20ma", "explicit", "FLOW_IN",
     ["J1 pin 3", "R3 pin 1 (250 ohm; R3 pin 2 is GND)", "U2 pin AIN0 (ADS1115 ADC input)"],
     ["J1 pin 4 is GND"],
     "J1 pin 3 is wired to the active 4-20 mA current output of a flow meter",
     "Active 4-20 mA output into a 250 ohm sense resistor."),
    ("L06", "loop_4_20ma", "explicit", "LOOP_RTN",
     ["J4 pin 4", "R7 pin 1 (250 ohm 0.1%; R7 pin 2 is AGND)", "U1 pin PA1 (MCU ADC input, through 1 kohm)"],
     ["J4 pin 3 is +24 V loop supply"],
     "J4 pins 3-4 are wired to a two-wire level transmitter (4-20 mA)",
     "Two-wire level transmitter loop return through 250 ohm."),
    ("L07", "loop_4_20ma", "implicit", "CH3",
     ["R44 pin 2 (10 ohm; R44 pin 1 is terminal J11 pin 5)", "R45 pin 1 (250 ohm 0.05% shunt; R45 pin 2 is GND)", "U8 pin AIN3 (ADS1115)"],
     ["J11 pin 6 is labelled 24V_LOOP", "U8 AIN2 is tied to the shunt's GND end (differential measurement)"],
     None,
     "Shunt of 250 ohm from a terminal next to a 24V_LOOP pin: current-loop receiver."),
    ("L08", "loop_4_20ma", "explicit", "AO_4_20",
     ["U12 pin IOUT (AD5420 current-output DAC, 4-20 mA range selected)", "J5 pin 1"],
     ["J5 pin 2 is the loop return"],
     "J5 is wired to a valve positioner's 4-20 mA input",
     "Current-output DAC in the 4-20 mA range driving a positioner's 4-20 mA input."),
    # ── relay_coil_drive ──────────────────────────────────────────────────
    ("R01", "relay_coil_drive", "explicit", "K1_COIL_LO",
     ["Q2 collector (BC547 NPN; emitter to GND)", "D5 anode (1N4007; D5 cathode to +12 V)", "K1 coil pin 2 (12 V relay coil, 400 ohm)"],
     ["K1 coil pin 1 is +12 V", "Q2 base is driven from MCU pin D7 through 1 kohm"],
     None,
     "Low-side transistor switch with flyback diode across a relay coil: switches a relay coil."),
    ("R02", "relay_coil_drive", "implicit", "N40",
     ["Q7 collector (MMBT2222A; emitter to GND)", "D12 anode (1N4148; cathode to +5 V)", "K3 pin 1 (G5LE-1 relay, coil)"],
     ["K3 pin 2 is +5 V"],
     None,
     "Transistor collector + reverse diode + relay coil pin."),
    ("R03", "relay_coil_drive", "explicit", "K5_A2",
     ["U6 pin 14 OUT3 (ULN2003A Darlington sink output)", "K5 coil terminal A2 (24 VDC relay coil)"],
     ["K5 coil terminal A1 is +24 V", "U6 pin 9 COM (internal clamp diodes) is +24 V", "U6 input 3 is MCU pin PB5"],
     None,
     "ULN2003A output with COM clamp to the coil supply, sinking a relay coil."),
    ("R04", "relay_coil_drive", "explicit", "DRV_K2",
     ["Q4 drain (AO3400 N-MOSFET; source to GND)", "D3 anode (SS14 Schottky; cathode to +24 V)", "K2 coil pin 1 (24 VDC relay coil)"],
     ["K2 coil pin 2 is +24 V", "Q4 gate is driven from MCU pin PA8 through 100 ohm with 100 kohm to GND"],
     None,
     "MOSFET low-side switch with Schottky flyback across a relay coil."),
    ("R05", "relay_coil_drive", "explicit", "RLY_A",
     ["Q9 drain (2N7002; source to GND)", "D8 anode (1N4148; cathode to +12 V)", "K4 coil pin A2 (relay that switches a damper actuator's 24 VAC)"],
     ["K4 coil pin A1 is +12 V"],
     None,
     "2N7002 low-side switch with flyback diode on the coil of the damper relay."),
    ("R06", "relay_coil_drive", "implicit", "N55",
     ["Q10 collector (BC337; emitter to GND)", "D9 anode (1N4007; cathode to VRELAY)", "J3 pin 2, labelled COIL-"],
     ["J3 pin 1, labelled COIL+, is VRELAY (+24 V)"],
     "J3 goes to an off-board relay",
     "Transistor + flyback diode + terminal pair labelled COIL+/COIL-: switches an off-board relay coil."),
    ("R07", "relay_coil_drive", "explicit", "K8_DRV",
     ["U15 pin OUT2 (TPL7407L low-side driver channel)", "K8 coil pin 1 (12 V relay coil)"],
     ["K8 coil pin 2 is +12 V", "U15 COM pin is +12 V (internal flyback clamps)"],
     None,
     "Low-side driver channel with COM clamp sinking a relay coil."),
    ("R08", "relay_coil_drive", "implicit", "N61",
     ["Q3 collector (BC337; emitter to GND)", "D7 anode (1N4007; cathode to +12 V)", "K6 pin 1 (coil)", "C20 pin 1 (100 nF snubber; C20 pin 2 is +12 V)"],
     ["K6 pin 2 is +12 V", "Q3 base from MCU pin PC1 through 2.2 kohm"],
     None,
     "Transistor, reverse diode and a relay coil pin: relay coil low side."),
    # ── field_input_24v ───────────────────────────────────────────────────
    ("F01", "field_input_24v", "explicit", "DI1",
     ["J6 pin 3", "R20 pin 1 (2.2 kohm; R20 pin 2 is U7 pin 1, the PC817 LED anode)"],
     ["U7 pin 2 (LED cathode) is J6 pin 4, the field 0 V", "U7 output transistor pulls MCU pin PB3 low against a 10 kohm pull-up to +3.3 V"],
     "J6 pin 3 is wired to the output of a 24 VDC PNP proximity sensor",
     "24 VDC sensor into an optocoupler LED through 2.2 kohm: receives a 24 V field signal."),
    ("F02", "field_input_24v", "implicit", "IN_4",
     ["J10 pin 4", "R33 pin 1 (3.3 kohm 0.5 W)"],
     ["R33 pin 2 is the anode of the LED in U12 (TLP291 optocoupler)", "U12 LED cathode goes to J10 pin 9, labelled COM",
      "a reverse diode is placed across U12's LED", "J10 pin 1 is labelled +24V"],
     None,
     "Terminal through a 3.3 kohm 0.5 W resistor into an opto LED, COM return, +24V terminal alongside: 24 V field input."),
    ("F03", "field_input_24v", "explicit", "X3",
     ["J2 pin 3", "R4 pin 1 (4.7 kohm)"],
     ["R4 pin 2 goes through a series diode to the anode of optocoupler U2's LED", "U2 LED cathode is J2 pin 10 (field 0 V)",
      "J2 pin 1 is +24 V, supplied to the field contacts"],
     "J2 pin 3 is wired to a float switch contact fed from J2 pin 1 (+24 VDC)",
     "24 VDC field contact into an opto input."),
    ("F04", "field_input_24v", "explicit", "START_PB",
     ["J8 pin 1", "R26 pin 1 (2.7 kohm; R26 pin 2 is the PC817 U9 LED anode)"],
     ["U9 LED cathode is the field 0 V terminal J8 pin 2"],
     "J8 pin 1 is wired to a pushbutton that switches +24 VDC from the panel supply",
     "Panel pushbutton switching +24 VDC into an opto LED."),
    ("F05", "field_input_24v", "implicit", "N70",
     ["J5 pin 2", "R60 pin 1 (2.2 kohm; R60 pin 2 is the IN pin of U20, an ISO1211 isolated 24 V digital-input receiver)"],
     ["U20 field-side ground is J5 pin 1", "U20 SENSE pin has its 562 ohm current-limit resistor"],
     None,
     "Terminal into an ISO1211 (isolated 24 V digital-input receiver) input: 24 V field input."),
    ("F06", "field_input_24v", "explicit", "LIMIT_SW",
     ["J7 pin 6", "R14 pin 1 (2.2 kohm; R14 pin 2 is the PC817 U4 LED anode)"],
     ["U4 LED cathode is J7 pin 7 (field 0 V)"],
     "J7 pin 6 is wired to a limit switch contact powered from the 24 VDC field supply",
     "Limit switch on 24 VDC into an opto LED."),
    ("F07", "field_input_24v", "implicit", "FIELD_IN2",
     ["J4 pin 2", "D30 cathode (SMBJ33A TVS; anode to field 0 V)", "R70 pin 1 (2.2 kohm; R70 pin 2 is opto U3 LED anode)"],
     ["J4 pin 1 is 24V+ supplied to sensors", "U3 LED cathode is field 0 V"],
     None,
     "Terminal next to a 24V+ sensor supply with a 33 V TVS and 2.2 kohm into an opto: 24 V field input."),
    ("F08", "field_input_24v", "explicit", "DOOR_SW",
     ["J3 pin 2", "R9 pin 1 (2.2 kohm; R9 pin 2 is PC817 U5 LED anode)"],
     ["U5 LED cathode is J3 pin 3 (field 0 V)", "J3 pin 1 is +24 VDC field supply"],
     "J3 pins 1-2 are wired across a dry-contact door switch",
     "Dry contact switching +24 VDC into an opto LED."),
    # ── logic_local ───────────────────────────────────────────────────────
    ("G01", "logic_local", "explicit", "SDA",
     ["U1 pin PB7 (STM32F411 I2C1 SDA)", "U5 pin 5 (24LC256 EEPROM SDA)", "R9 pin 1 (4.7 kohm; R9 pin 2 is +3.3 V)"],
     [], None, "On-board I2C data line between MCU and EEPROM."),
    ("G02", "logic_local", "explicit", "LED_STATUS_DRV",
     ["U1 pin PA5 (MCU GPIO)", "R12 pin 1 (330 ohm)"],
     ["R12 pin 2 goes to the anode of on-board status LED D2; D2 cathode is GND"], None, "MCU GPIO to an on-board LED."),
    ("G03", "logic_local", "explicit", "SPI_SCK",
     ["U1 pin PA5 (SPI1 SCK)", "U6 pin 6 (W25Q32 SPI flash CLK)"], [], None, "On-board SPI clock to flash."),
    ("G04", "logic_local", "implicit", "OPTO_OUT1",
     ["U7 pin 4 (PC817 phototransistor collector; emitter pin 3 is GND)", "R21 pin 1 (10 kohm; R21 pin 2 is +3.3 V)", "U1 pin PB3 (MCU input)"],
     [], None, "Logic side of an optocoupler: collector, pull-up and MCU input, all on board."),
    ("G05", "logic_local", "explicit", "NRST",
     ["U1 pin NRST", "R2 pin 1 (10 kohm; R2 pin 2 is +3.3 V)", "C3 pin 1 (100 nF; C3 pin 2 is GND)", "SW1 pin 1 (reset button; SW1 pin 2 is GND)"],
     [], None, "On-board reset net."),
    ("G06", "logic_local", "explicit", "UART_TX",
     ["U1 pin PA2 (USART2 TX)", "U4 pin 4 (MAX3485 DI, driver input)"], [], None, "MCU UART to an on-board transceiver's logic input."),
    ("G07", "logic_local", "explicit", "DE_RE",
     ["U1 pin PB0 (MCU GPIO)", "U4 pin 3 (MAX3485 DE)", "U4 pin 2 (MAX3485 /RE)"], [], None, "On-board transceiver direction control."),
    ("G08", "logic_local", "implicit", "BTN_SELECT",
     ["SW3 pin 1 (tactile switch; SW3 pin 2 is GND)", "R40 pin 1 (10 kohm; R40 pin 2 is +3.3 V)", "C41 pin 1 (100 nF; C41 pin 2 is GND)", "U1 pin PC4 (MCU input)"],
     [], None, "On-board pushbutton with pull-up and debounce."),
    # ── undeclared (genuinely ambiguous) ──────────────────────────────────
    ("U01", "undeclared", "ambiguous", "N80",
     ["U1 pin PA4 (MCU pin with DAC capability)", "J9 pin 2"], ["J9 pin 1 is GND"], None,
     "An MCU pin straight to a connector: level, direction and purpose not determined."),
    ("U02", "undeclared", "ambiguous", "N81",
     ["J12 pin 3", "R70 pin 1 (1 kohm; R70 pin 2 is MCU pin PB12)"], ["J12 pin 4 is GND"], None,
     "Terminal to an MCU pin through 1 kohm: input or output, level unknown."),
    ("U03", "undeclared", "ambiguous", "N82",
     ["Q12 collector (NPN; emitter to GND)", "J14 pin 1"], ["Q12 base from MCU through 1 kohm", "no diode on the board"], None,
     "Open-collector output to a connector; the off-board load is unknown (could be a lamp, relay, buzzer...)."),
    ("U04", "undeclared", "ambiguous", "N83",
     ["J16 pin 1", "R80 pin 1 (100 kohm; R80 pin 2 is MCU ADC pin PA1)"], ["33 kohm from PA1 to GND", "J16 pin 2 is GND"], None,
     "A divided analog input from a terminal: source unknown (battery monitor, 0-10 V sensor, ...)."),
    ("U05", "undeclared", "ambiguous", "N84",
     ["U1 pin PB8 (MCU GPIO)", "R81 pin 1 (470 ohm; R81 pin 2 is J18 pin 3)"], ["J18 pin 1 is +5 V", "J18 pin 2 is GND"], None,
     "A three-pin header with a signal through 470 ohm: purpose unknown."),
    ("U06", "undeclared", "ambiguous", "N85",
     ["J20 pin 1", "J21 pin 1"], ["nothing else on the board connects to this net"], None,
     "A pass-through between two terminals: role set by the field wiring, which is not described."),
    ("U07", "undeclared", "ambiguous", "N86",
     ["Q20 drain (N-MOSFET; source to GND)", "J22 pin 2"], ["J22 pin 1 is +24 V", "no flyback diode on the board", "Q20 gate from MCU"], None,
     "A low-side switch for an unspecified off-board 24 V load (lamp, solenoid, relay...)."),
    ("U08", "undeclared", "ambiguous", "N87",
     ["U1 pin PA8 (MCU timer output)", "R90 pin 1 (10 kohm; R90 pin 2 is J23 pin 1)"], ["J23 pin 2 is GND"], None,
     "A timer output through 10 kohm to a connector: purpose unknown."),
    # ── out of set (a role the label set does not contain) ────────────────
    ("O01", "out_of_set", "out_of_set", "RTD_A",
     ["J3 pin 1", "U10 pin OUT (REF200 1 mA current source)", "U11 pin AIN0+ (ADS1220 ADC)"],
     ["J3 pins 1-2 are wired to a PT100 RTD", "J3 pin 2 goes to U11 AIN0- and a reference resistor to GND"], None,
     "RTD excitation and sense (not in the label set)."),
    ("O02", "out_of_set", "out_of_set", "THERM1",
     ["J4 pin 1", "R15 pin 1 (10 kohm; R15 pin 2 is +3.3 V)", "U1 pin PA0 (MCU ADC)"],
     ["J4 pins 1-2 are wired to a 10 kohm NTC thermistor; J4 pin 2 is GND"], None,
     "NTC thermistor divider input (not in the label set)."),
    ("O03", "out_of_set", "out_of_set", "AI_HUM",
     ["J5 pin 1", "R16 pin 1 (100 kohm; R16 pin 2 is MCU ADC pin PA2, with 47 kohm from PA2 to GND)"], ["J5 pin 2 is GND"],
     "J5 is wired to the 0-10 V output of a humidity transmitter",
     "A 0-10 V *input* (the set only has a 0-10 V output role)."),
    ("O04", "out_of_set", "out_of_set", "FAN_PWM",
     ["U1 pin PA6 (timer PWM output, 25 kHz)", "Q30 gate (open-drain buffer)", "J6 pin 4 via Q30 drain"], ["J6 pin 1 is GND"],
     "J6 is wired to a 4-wire PC fan's PWM control input",
     "PC-fan PWM control (not in the label set)."),
]

# Hand-written paraphrases (prose, different ordering) for a pre-registered subset: 2 per in-set class.
PARAPHRASES = {
    "A02": "Net OUT_A: an LM2904 op-amp (U2, on a +15 V rail) wired as a non-inverting stage with gain 3.0 (20 kohm over 10 kohm) takes the MCU DAC's 0-3.3 V and, through a 47 ohm resistor (R8), feeds terminal J1 pin 2. A 12 V TVS clamps that terminal to ground, and J1 pin 1 is ground.",
    "A06": "Net VFD_REF runs from the output of an LT1013 op-amp (U11, powered from +24 V) through a 100 ohm resistor R40 to terminal J7 pin 1 (J7 pin 2 is ground). In the field, J7 connects to a drive whose analog input is set to 'voltage, 0-10 V'.",
    "L02": "Net SENSE1: terminal J6 pin 2 passes through PTC fuse F3 onto a node that has a 250 ohm 0.1 % resistor (R11) to ground, a TVS diode to ground, and a 22 kohm resistor to ADC pin A1. The neighbouring terminal J6 pin 1 carries +24 V.",
    "L05": "Net FLOW_IN joins terminal J1 pin 3, the top of R3 (250 ohm, bottom end grounded) and ADC channel AIN0 of an ADS1115. The field cable on J1 pin 3 comes from a flow meter's active 4-20 mA output; J1 pin 4 is ground.",
    "R01": "Net K1_COIL_LO: the collector of an NPN BC547 (Q2, emitter grounded, base driven from MCU D7 via 1 kohm), the anode of a 1N4007 whose cathode sits on +12 V, and pin 2 of relay K1's 400 ohm, 12 V coil (coil pin 1 on +12 V).",
    "R04": "Net DRV_K2 ties together the drain of an AO3400 MOSFET (source grounded, gate from PA8 via 100 ohm with a 100 kohm pull-down), the anode of an SS14 Schottky returning to +24 V, and one end of relay K2's 24 VDC coil, whose other end is on +24 V.",
    "F01": "Net DI1: screw terminal J6 pin 3, which the installer wires to a 24 VDC PNP proximity sensor's output, feeds a 2.2 kohm resistor into the LED anode of PC817 U7; the LED cathode returns to field 0 V on J6 pin 4, and U7's transistor pulls MCU pin PB3 low against 10 kohm to 3.3 V.",
    "F05": "Net N70 connects terminal J5 pin 2 to a 2.2 kohm resistor that enters the IN pin of U20, an ISO1211 isolated 24 V digital-input receiver whose field-side ground is J5 pin 1 (its SENSE pin carries the 562 ohm current-limit resistor).",
    "G01": "Net SDA links the STM32F411's I2C1 data pin PB7 to pin 5 of a 24LC256 EEPROM, with a 4.7 kohm pull-up to 3.3 V.",
    "G04": "Net OPTO_OUT1: the collector of a PC817's phototransistor (U7 pin 4, emitter grounded) meets a 10 kohm pull-up to 3.3 V and MCU input PB3.",
    "U03": "Net N82: the collector of an NPN transistor Q12 (emitter grounded, base driven from the MCU via 1 kohm) goes straight to connector J14 pin 1. There is no diode on the board.",
    "U07": "Net N86 joins the drain of an N-channel MOSFET Q20 (source grounded, gate from the MCU) and pin 2 of connector J22, whose pin 1 carries +24 V. The board has no flyback diode.",
}


#: Does the net *name* hint at the role? Recorded for analysis (a confound, not a label).
NAME_HINT = {
    "A01": "weak", "A02": "none", "A03": "strong", "A04": "none", "A05": "strong", "A06": "strong", "A07": "none", "A08": "strong",
    "L01": "weak", "L02": "weak", "L03": "weak", "L04": "none", "L05": "weak", "L06": "strong", "L07": "none", "L08": "strong",
    "R01": "strong", "R02": "none", "R03": "weak", "R04": "weak", "R05": "strong", "R06": "none", "R07": "weak", "R08": "none",
    "F01": "weak", "F02": "weak", "F03": "none", "F04": "weak", "F05": "none", "F06": "weak", "F07": "strong", "F08": "weak",
    "G01": "strong", "G02": "strong", "G03": "strong", "G04": "weak", "G05": "strong", "G06": "strong", "G07": "strong", "G08": "strong",
    "U01": "none", "U02": "none", "U03": "none", "U04": "none", "U05": "none", "U06": "none", "U07": "none", "U08": "none",
    "O01": "strong", "O02": "strong", "O03": "weak", "O04": "strong",
}


def state_of(net, pins, hop, field):
    s = {"net": net, "pins_on_this_net": pins}
    if hop:
        s["one_hop_context"] = hop
    if field:
        s["field_wiring"] = field
    return s


def main():
    items = []
    for iid, truth, diff, net, pins, hop, field, why in ITEMS:
        item = {
            "id": f"P1-{iid}", "state": state_of(net, pins, hop, field),
            "question_fill": {"net": net},
            "truth": {"net_role": truth}, "difficulty": diff, "name_hint": NAME_HINT[iid], "derivation": why,
            "scored": truth != "out_of_set",
        }
        if iid in PARAPHRASES:
            item["paraphrase_state"] = {"net": net, "description": PARAPHRASES[iid]}
        items.append(item)
    ids = [i["id"] for i in items]
    write_set("p1_net_role", {
        "task": "P1 net_role for generic digital/analog nets (Choice over the B14 enum + undeclared)",
        "questions": QUESTIONS,
        "label_space": list(QUESTIONS["net_role"]["criteria"]),
        "truth_rule": ("Each net is constructed as the circuit that implements the named role, per the B14 label "
                       "definitions. 'undeclared' items are built so that the connections do not fix the role (off-board "
                       "load or level unknown). 'out_of_set' items implement a role the enum lacks; they are scored "
                       "separately (only 'undeclared' is non-false for them)."),
        "strictness_order": {"logic_local": 1, "analog_0_10v_out": 2, "loop_4_20ma": 2, "relay_coil_drive": 3,
                             "field_input_24v": 3, "undeclared": 3},
        "strictness_note": ("Pre-registered for the stricter-option analysis: field-wired roles need surge/spacing "
                            "constraints that board-local logic does not; an unknown role is treated as the strictest. "
                            "An unsafe error is a final label whose strictness is below the truth's."),
        "citations": cite("TEMPLATE_B14", "WIKI_CURRENT_LOOP", "TI_SLLA370", "PRODUCT_MASTER"),
        "variants": {
            "repeat_subset": pick_subset(ids, 13, "p1_repeat"),
            "paraphrase_subset": sorted(i["id"] for i in items if "paraphrase_state" in i),
            "blind_subset": pick_subset(ids, 3, "p1_blind"),
        },
        "items": items,
    })


if __name__ == "__main__":
    main()
