"""run_and_analyze.py — send P1–P4 label sets to Jev (orig, rev, rep and para subsets), log to results.jsonl,
score against constructed truth, write RESULTS.md. Re-running skips requests already logged."""
import asyncio, collections, copy, hashlib, json, pathlib, sys
H = pathlib.Path(__file__).resolve().parent
OUT = H / "results.jsonl"
SETS = ["p1_net_role", "p2_env", "p3_isolation", "p4_standard"]
NMI = "need_more_information"

def rev(qs):
    qs = copy.deepcopy(qs)
    for q in qs.values():
        if q["type"] == "choice": q["criteria"] = dict(reversed(list(q["criteria"].items())))
    return qs

def questions(d, it):
    if "questions" in it: return it["questions"]
    if "question_sets" in d: return d["question_sets"][it["kind"]]
    qs = copy.deepcopy(d["questions"])
    for q in qs.values(): q["instructions"] = q["instructions"].format(**it.get("question_fill", {}))
    return qs

def plan():
    reqs = []
    for s in SETS:
        d = json.loads((H / "sets" / f"{s}.json").read_text())
        v = d["variants"]
        for it in d["items"]:
            qs = questions(d, it)
            reqs += [(s, it["id"], "orig", it["state"], qs), (s, it["id"], "rev", it["state"], rev(qs))]
            if it["id"] in v.get("repeat_subset", []): reqs.append((s, it["id"], "rep", it["state"], qs))
            if it["id"] in v.get("paraphrase_subset", []) and it.get("paraphrase_state"):
                reqs.append((s, it["id"], "para", it["paraphrase_state"], qs))
    return reqs

async def run():
    from typesafe_sdk import AsyncTypeSafeClient
    done = set()
    if OUT.exists():
        done = {(r["set"], r["id"], r["variant"]) for r in map(json.loads, OUT.read_text().splitlines()) if r.get("answers")}
    todo = [r for r in plan() if r[:3] not in done]
    print(len(todo), "to send")
    sem = asyncio.Semaphore(8)
    async with AsyncTypeSafeClient() as c:
        async def one(s, i, v, st, qs):
            async with sem:
                row = {"set": s, "id": i, "variant": v, "state_sha256": hashlib.sha256(json.dumps(st, sort_keys=True).encode()).hexdigest()}
                try:
                    r = await c.system_one(st, qs, model="jev-1.13.0")
                    row.update(model_resolved=r.model, usage=r.usage.model_dump(),
                               answers={k: a.model_dump(mode="json") for k, a in r.answers.items()})
                except Exception as e:
                    row["error"] = str(e)[:300]
                with OUT.open("a") as f: f.write(json.dumps(row) + "\n")
        await asyncio.gather(*(one(*r) for r in todo))

def top(a):
    return a["choice"] if a["type"] == "choice" else a["noul"] > .5

def analyze():
    R = [json.loads(l) for l in OUT.read_text().splitlines()]
    A = {(r["set"], r["id"], r["variant"]): r["answers"] for r in R if r.get("answers")}
    out = ["# Phase 3 / assurance labels (P1–P4) — results\n",
           f"Generated by `run_and_analyze.py`. {len(R)} requests, {sum(1 for r in R if r.get('error'))} errors, "
           f"{sum(r['usage']['input_tokens'] for r in R if r.get('usage')):,} input tokens. Truth is constructed from standard text / circuit construction "
           "(see each set's `truth_rule`, `citations`), never from Jev. R7 (refusal) is not included: its generator fails its own self-check (item W02 is accepted by the real registry).\n",
           "| Set | Question | n scored | accuracy (orig) | same answer orig/rev | stable across rep/para | accuracy when p_top ≥ 0.9 (coverage) |\n|---|---|---|---|---|---|---|"]
    W = out.append; conf = collections.defaultdict(collections.Counter)
    for s in SETS:
        d = json.loads((H / "sets" / f"{s}.json").read_text())
        keys = sorted({k for it in d["items"] for k in it["truth"]})
        for k in keys:
            n = c = st = sn = sx = hi = hic = 0
            for it in d["items"]:
                t = it["truth"].get(k)
                o = A.get((s, it["id"], "orig"), {}).get(k)
                if t is None or o is None or it.get("scored") is False or (k == "standard_family_flag" and it.get("family_contested")): continue
                n += 1; ok = top(o) == t; c += ok; conf[(s, k)][(t, top(o))] += 1
                rv = A.get((s, it["id"], "rev"), {}).get(k); st += rv is not None and top(rv) == top(o)
                for v in ("rep", "para"):
                    x = A.get((s, it["id"], v), {}).get(k)
                    if x is not None: sn += 1; sx += top(x) == top(o)
                if o["type"] == "choice" and max(o["probabilities"].values()) >= .9: hi += 1; hic += ok
            if n: W(f"| {s} | {k} | {n} | {c}/{n} = {100*c/n:.0f} % | {st}/{n} | {sx}/{sn} | " + (f"{hic}/{hi} ({hi}/{n})" if hi else "—") + " |")
    W("\n## Errors (truth → Jev: count)\n")
    for (s, k), cc in conf.items():
        w = [f"{t}→{j}: {m}" for (t, j), m in cc.most_common() if t != j]
        if w: W(f"- **{s} / {k}**: " + "; ".join(w))
    d = json.loads((H / "sets" / "p1_net_role.json").read_text())
    oos = [it for it in d["items"] if it["truth"]["net_role"] == "out_of_set"]
    W(f"\nP1 out-of-set nets (role not in the enum; the safe answer is `undeclared`): "
      + ", ".join(f"{it['id']}→{A.get(('p1_net_role', it['id'], 'orig'), {}).get('net_role', {}).get('choice')}" for it in oos))
    (H / "RESULTS.md").write_text("\n".join(out) + "\n"); print("\n".join(out))

if __name__ == "__main__":
    if "--analyze-only" not in sys.argv: asyncio.run(run())
    analyze()
